UPLOAD_FOLDER = 'tmp/uploads/'
TEMP_FOLDER = 'tmp/temp_png/'
PROCESSED_FOLDER = 'tmp/processed/'
DEFAULT_FOLDER = 'tmp/processed/manual_sort/'
ZIP_DOWNLOAD = 'tmp/zip_download/'
OCR_OUTPUT_FILE = 'ocr'