folders:
    HIPPA:
        - MEDICARE ADMINISTRATIVE
    
    Bill of Rights:
        - BILL OF RIGHTS

    Privacy Practice:
        - TOLL

    ABN:
        - ABN

    Capped Rental:
        - CAPPED RENTAL

    Equipment Warranty:
        - EQUIPMENT WARRANTY

    Supplier Standards:
        - SUPPLIER STANDARDS